version: "3.9"
services:
  database:
    image: postgres:16
    container_name: esgi-rent-db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_PASSWORD:-user}
      POSTGRES_DB: ${DB_NAME:-esgi_rent_db}